development:
  password: ${STAGING_PWD}
  theme_id: "99904585892"
  store: dev-store-00002.myshopify.com
staging:
  password: ${STAGING_PWD}
  theme_id: "99904585892"
  store: dev-store-00002.myshopify.com
production:
  password: ${PRODUCTION_PWD}
  theme_id: "99695394977"
  store: dev-store-00001.myshopify.com
